# Homebridge Helm Chart Values
# Generated by Terraform for tf-kube-any-compute

# Image configuration
image:
  repository: homebridge/homebridge
  tag: "latest"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 8581

# Deployment configuration
replicaCount: 1

# Resource configuration
resources:
  limits:
    cpu: ${cpu_limit}
    memory: ${memory_limit}
  requests:
    cpu: ${cpu_request}
    memory: ${memory_request}

# Node selector for architecture
%{ if length(node_selector) > 0 }
nodeSelector:
%{ for key, value in node_selector }
  ${key}: ${value}
%{ endfor }
%{ endif }

# Host network configuration
hostNetwork: ${enable_host_network}

# Persistence configuration
%{ if enable_persistence }
persistence:
  enabled: true
  storageClass: ${storage_class}
  size: ${persistent_disk_size}
  accessMode: ReadWriteOnce
%{ else }
persistence:
  enabled: false
%{ endif }

# Environment variables
env:
  - name: HOMEBRIDGE_CONFIG_UI
    value: "1"
  - name: HOMEBRIDGE_CONFIG_UI_PORT
    value: "8581"

# Homebridge configuration
config:
  bridge:
    name: "Homebridge"
    username: "CC:22:3D:E3:CE:30"
    port: 51826
    pin: "031-45-154"
  
  accessories: []
  
  platforms:
    - platform: "config"
      name: "Config"
      port: 8581
      auth: "form"
      theme: "auto"
      tempUnits: "c"
      lang: "auto"

# Plugin configuration
%{ if plugins != "[]" }
plugins: ${plugins}
%{ endif }

# Security context
securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

# Pod security context
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

# Probes
livenessProbe:
  httpGet:
    path: /
    port: 8581
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8581
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5