extends: default

rules:
  line-length:
    max: 160
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy: disable
  brackets:
    max-spaces-inside: 1
  indentation:
    spaces: 2
