name: Quick Tests

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'

env:
  TF_VERSION: "1.12.2"
  CI: "true"

jobs:
  quick-validation:
    name: ⚡ Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Quick Validation
      run: |
        terraform fmt -check -recursive
        terraform init -backend=false
        terraform validate

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.55.0

    - name: Quick Lint
      run: |
        tflint --init
        tflint -f compact

        # Lint all submodules
        for dir in helm-*/; do
          if [ -d "$dir" ]; then
            echo "Linting $dir"
            cd "$dir"
            tflint --init
            tflint -f compact
            cd ..
          fi
        done

    - name: Summary
      run: |
        echo "## ⚡ Quick Tests Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Format Check**: PASSED" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Validation**: PASSED" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Linting**: PASSED" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "🚀 **Ready for comprehensive testing!**" >> $GITHUB_STEP_SUMMARY
