name: Terraform Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CI: "true"
  GITHUB_ACTIONS: "true"
  MICROK8S_CHANNEL: "1.28/stable"

jobs:
  terraform-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MicroK8s for CI
      run: |
        sudo snap install microk8s --classic --channel=${{ env.MICROK8S_CHANNEL }}
        sudo microk8s status --wait-ready --timeout=300
        sudo microk8s enable dns
        sudo usermod -a -G microk8s $USER
        mkdir -p ~/.kube
        sudo microk8s config > ~/.kube/config
        sudo microk8s config > ~/.kube/default-config
        chmod 600 ~/.kube/config ~/.kube/default-config

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Run Unit Tests
      run: make test-unit

    - name: Run Regression Tests
      run: make test-regression

    - name: Generate Test Report
      if: always()
      run: make test-report

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.json
